/**
 * 这边放双工通道的KEY值
 * 每个key值记得写备注是代表什么
 */

// 通用的订阅事件key
export enum SUBSCRIPTION_KEYS {
  ENV_STARTING = 'ENV_STARTING', // 启动环境的订阅
  ENV_CLOSE_DATA_SYNC = 'ENV_CLOSE_DATA_SYNC', // 关闭环境数据同步事件
  BOOKMARK_ADD_EVENT = 'BOOKMARK_ADD_EVENT', // 新建书签触发渲染进程的事件
  BOOKMARK_RENAME_EVENT = 'BOOKMARK_RENAME_EVENT', // 修改书签/文件夹名称事件
  BOOKMARK_DELETE_EVENT = 'BOOKMARK_DELETE_EVENT', // 删除书签/文件夹事件
  BOOKMARK_RIGHT_CLICK_ADD_EVENT = 'BOOKMARK_RIGHT_CLICK_ADD_EVENT', // 右键新建书签触发渲染进程的事件
  BOOKMARK_RIGHT_CLICK_ADD_FOLDER_EVENT = 'BOOKMARK_RIGHT_CLICK_ADD_FOLDER_EVENT', // 右键新建文件夹触发渲染进程的事件
  SYNC_TAB_LIST = 'SYNC_TAB_LIST', // 同步渲染进程的页眉tab列表
  TAB_ITEM_EDIT = 'TAB_ITEM_EDIT', // tab单个编辑事件
  WINDOW_RESIZE_LISTENER = 'WINDOW_RESIZE_LISTENER' // 窗口尺寸变化事件
}

// 通用的请求事件key
export enum REQUEST_KEYS {}

// 这边放置升级的事件key
export enum UPDATE_KEYS {
  UPDATE_CHECK = 'UPDATE_CHECK',
  UPDATE_AVAILABLE = 'UPDATE_AVAILABLE',
  UPDATE_NOT_AVAILABLE = 'UPDATE_NOT_AVAILABLE',
  UPDATE_DOWNLOAD = 'UPDATE_DOWNLOAD',
  UPDATE_DOWNLOAD_PROGRESS = 'UPDATE_DOWNLOAD_PROGRESS',
  UPDATE_DOWNLOAD_COMPLETE = 'UPDATE_DOWNLOAD_COMPLETE',
  UPDATE_DOWNLOAD_ERROR = 'UPDATE_DOWNLOAD_ERROR',
  UPDATE_DOWNLOAD_CANCEL = 'UPDATE_DOWNLOAD_CANCEL',
  KERNEL_UPDATE_DOWNLOAD_PROGRESS = 'KERNEL_UPDATE_DOWNLOAD_PROGRESS'
}
